Homework 3
kosmos1308/FocusStartHomeworks pull request #6
Opened 2021-11-16 16:32 UTC by kosmos1308

Homework 3
CV

2021-11-17 06:58 UTC, c0dedbear requested changes
Выглядит неплохо.
По проекту есть замечания - смотри комменты большинство комментов так относятся и к другим файлам. Ну и первая домашка зачем то в этом пуле появилась.

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
final здесь и в других местах

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/AppDelegate.swift
> +        // Called when the user discards a scene session.
пустые методы не нужно оставлять

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/CVViewController.swift
> +    let swiftLabel = UILabel()
почему не private?

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/CVViewController.swift
> +        setupScrollViewAutoLayout()         // scrollView
из названий методов и так понятно что к чему относится, комментарии лишние.

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/CVViewController.swift
> +    }
классический пример Massive View Controller.

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/HobbyViewController.swift
> +    private var hobbyImageArray = ["football", "tennis", "coding"]
они разве изменяются?

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/HobbyViewController.swift
> +        hobbyView.layer.cornerRadius = 10
магические цифры

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/SkillsViewController.swift
> +    private let left: CGFloat = 20
лучше в отдельный enum Metrics

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Controllers/SkillsViewController.swift
> +extension SkillsViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
хорошая практика это когда один экстеншен конформит один протокол.

2021-11-17 06:58 UTC, c0dedbear commented on cv/cv/Model/Contacts.swift
> +    init(phone: String, email: String, telegram: String) {
почему в качестве контейнера для данных class?

2021-11-17 06:58 UTC, c0dedbear commented on homework_1/homework_1/SceneDelegate.swift
> +//  homework_1
а зачем в этом пуле ДЗ  - 1???

2021-11-17 21:35 UTC, kosmos1308 commented on cv/cv/Controllers/SkillsViewController.swift
> +extension SkillsViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
исправил

2021-11-17 21:35 UTC, kosmos1308 commented on cv/cv/Model/Contacts.swift
> +    init(phone: String, email: String, telegram: String) {
исправил на struct

2021-11-17 21:35 UTC, kosmos1308 commented on cv/cv/Controllers/SkillsViewController.swift
> +    private let left: CGFloat = 20
создал enum и заменил constans

2021-11-17 21:35 UTC, kosmos1308 commented on cv/cv/Controllers/HobbyViewController.swift
> +    private var hobbyImageArray = ["football", "tennis", "coding"]
Нет, исправил на let

2021-11-17 21:36 UTC, kosmos1308 commented on cv/cv/Controllers/CVViewController.swift
> +        setupScrollViewAutoLayout()         // scrollView
удалил

2021-11-17 21:36 UTC, kosmos1308 commented on cv/cv/Controllers/CVViewController.swift
> +    let swiftLabel = UILabel()
исправил.

2021-11-17 21:36 UTC, kosmos1308 commented on cv/cv/AppDelegate.swift
> +        // Called when the user discards a scene session.
удалил

2021-11-17 21:36 UTC, kosmos1308 commented on cv/cv/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
исправил

2021-11-18 05:21 UTC, c0dedbear requested changes

2021-11-18 05:21 UTC, c0dedbear commented on cv/cv/Model/Metrics.swift
> +    //case height = 100
Закомментированый код не допускается. Статика не хранится в кейсах.
Вместо кейсов сделай static let, а то это легкое извращение, ты каждый раз rawValue дергаешь.

2021-11-18 06:54 UTC, kosmos1308 commented on homework_1/homework_1/SceneDelegate.swift
> +//  homework_1
удалил homework_1

2021-11-18 07:14 UTC, kosmos1308 commented on cv/cv/Model/Metrics.swift
> +    //case height = 100
сделал static let и удалил rawValue

2021-11-18 08:19 UTC, c0dedbear commented on cv/cv/Model/Person.swift
> +class Person {
почему здесь класс для данных?

2021-11-18 08:58 UTC, kosmos1308 commented on cv/cv/Controllers/CVViewController.swift
> +    }
CVViewController разбил на несколько VC(PersonVC, SkillVC, ExperienceVC, ContactVC)

2021-11-18 11:09 UTC, kosmos1308 commented on cv/cv/Model/Person.swift
> +class Person {
Потому что Person подразумевается только один. Использовать лучше struct?

2021-11-18 11:12 UTC, kosmos1308 commented on cv/cv/Controllers/HobbyViewController.swift
> +        hobbyView.layer.cornerRadius = 10
исправил

2021-11-18 11:39 UTC, c0dedbear commented on cv/cv/Model/Person.swift
> +class Person {
один в нескольких местах?

2021-11-18 11:46 UTC, kosmos1308 commented on cv/cv/Model/Person.swift
> +class Person {
в проекте он только в одном месте

2021-11-20 08:41 UTC, c0dedbear requested changes
не все маг цифры вынесены в константы/метрики, не у всех классов final

2021-11-21 15:43 UTC, c0dedbear commented
Принято

2021-11-21 15:43 UTC, merged